triggers:
  # Game defaults should be for SYNC. Triggers will set ASYNC options.
  # Consider weighting devastating options in case a game is rolled multiple times.
  - option_category: null
    option_name: async
    option_result: true
    options:
      null:
        per_game_name: true

  # I don't think there's a better way to do this to keep the async trigger standalone.
  # Must resist ReSuffix and PrefixPod. Minifying these breaks generation.
  - option_name: per_game_name
    option_result: false
    options:
      null:
        name: RePod{NUMBER}
