name: RePod{NUMBER}
game: A Hat in Time
async: false
per_game_name: false

A Hat in Time:
  # https://archipelago.gg/tutorial/A%20Hat%20in%20Time/setup/en
  # tldr tcplink beta branch + workshop mod
  progression_balancing: random-low
  accessibility: items
  death_link: false
  EndGoal: finale
  ShuffleAlpineZiplines: false
  LogicDifficulty: normal
  ShuffleStorybookPages: true
  ShuffleActContracts: true
  ShuffleSubconPaintings: false
  NoPaintingSkips: false
  CTRLogic: time_stop_only
  MinPonCost: 75
  MaxPonCost: 300
  BadgeSellerMinItems: 4
  BadgeSellerMaxItems: 8
  ActRandomizer: light
  FinaleShuffle: false
  StartingChapter: 1
  LowestChapterCost: 5
  HighestChapterCost: 25
  ChapterCostIncrement: 4
  ChapterCostMinDifference: 4
  FinalChapterMinCost: 30
  FinalChapterMaxCost: 35
  YarnBalancePercent: 20
  TimePieceBalancePercent: 35
  RandomizeHatOrder: true
  UmbrellaLogic: false
  StartWithCompassBadge: true
  CompassBadgeMode: closest
  MaxExtraTimePieces: 16
  YarnCostMin: 4
  YarnCostMax: 8
  YarnAvailable: 50
  MinExtraYarn: 10
  HatItems: false
  EnableDLC1: false
  Tasksanity: false
  TasksanityTaskStep: 1
  TasksanityCheckCount: 18
  ExcludeTour: false
  ShipShapeCustomTaskGoal: 0
  EnableDLC2: false
  BaseballBat: false
  MetroMinPonCost: 50
  MetroMaxPonCost: 200
  NyakuzaThugMinShopItems: 2
  NyakuzaThugMaxShopItems: 4
  NoTicketSkips: false
  EnableDeathWish: false
  DWShuffle: false
  DWShuffleCountMin: 18
  DWShuffleCountMax: 25
  DeathWishOnly: false
  DWEnableBonus: false
  DWAutoCompleteBonuses: true
  DWExcludeAnnoyingContracts: true
  DWExcludeAnnoyingBonuses: true
  DWExcludeCandles: true
  DWTimePieceRequirement: 15
  TrapChance: 0
  BabyTrapWeight: 40
  LaserTrapWeight: 40
  ParadeTrapWeight: 20
  start_inventory: {}

triggers:
  - option_category: null
    option_name: async
    option_result: true
    options:
      A Hat in Time:
        death_link: true
  - option_name: game
    option_result: A Hat in Time
    options:
      null:
        name: RePodHIT{NUMBER}
  - option_name: per_game_name
    option_result: false
    options:
      null:
        name: RePod{NUMBER}
