name: RePod{NUMBER}
game: ANIMAL WELL
async: false
per_game_name: true
description: "Unsupported https://github.com/ScipioWright/Archipelago-SW/releases/latest"

ANIMAL WELL:
  progression_balancing: random-low
  accessibility: random
  goal:
    fireworks: 1
    egg_hunt: 3
  key_ring: true
  matchbox: true
  candle_checks: true
  bunnies_as_checks: off
  bunny_warps_in_logic: false
  exclude_song_chests: true
  random_final_egg_location: false
  death_link: false
  bubble_jumping: exclude_long_chains
  disc_hopping: off
  wheel_tricks: off
  weird_tricks: false

triggers:
  - option_category: null
    option_name: async
    option_result: true
    options:
      ANIMAL WELL:
        goal:
          fireworks: 3
          egg_hunt: 1
        key_ring:
          false: 1
          true: 3
        matchbox:
          false: 1
          true: 3
        candle_checks: true
        bunnies_as_checks: exclude_tedious # forces bunny_warps_in_logic true
        exclude_song_chests: false
        disc_hopping: single
        weird_tricks: true # https://www.youtube.com/playlist?list=PL-YW4GNIhXnrXszgntzCGw2SoLcmRElKY
        death_link: true
  - option_name: game
    option_result: ANIMAL WELL
    options:
      null:
        name: RePodWell{NUMBER}
  - option_name: per_game_name
    option_result: false
    options:
      null:
        name: RePod{NUMBER}
