name: RePod{NUMBER}
game: Jigsaw
async: false
per_game_name: true
description: "Unsupported https://github.com/spineraks-org/ArchipelagoJigsaw/releases/latest"
weight: 1

Jigsaw:
  # https://jigsaw-ap.netlify.app/
  progression_balancing: random-range-low-0-50
  accessibility: random
  number_of_pieces: random-range-low-130-250 # 4-50-2000
  orientation_of_image: landscape # square/landscape/portrait, hopefully this moves to the client one day
  which_image:
    37: 1
    39: 1
  allow_filler_items: false 
  percentage_of_merges_that_are_checks: 100 # 10-100
  maximum_number_of_checks: 100 # 25-1000, overrides percentage_of_merges_that_are_checks. deflates large piece count ratio, may bundle pieces into single items
  percentage_of_extra_pieces: 25 # 0-100
  piece_order_type: # prioritized over piece_order
    random_order: 3
    corners_edges_normal: 1
    normal_edges_corners: 1
    edges_normal_corners: 1
    corners_normal_edges: 1
    normal_corners_edges: 1
    edges_corners_normal: 1
  strictness_piece_order_type: 100 # 1-100, how strict to follow above piece_order_type. barely~strictest
  piece_order:
    random_order: 1          # receive in random order with no extra constraints whatsoever
    every_piece_fits: 2      # every piece you receive, will be able to merge with another piece
    least_merges_possible: 2 # receive in an order that gives the least number of possible merges
  strictness_piece_order: 100 # 1-100, how strict to follow above piece_order. barely~strictest
  number_of_checks_out_of_logic: random-low # 1-10
  death_link: 10

triggers:
  - option_category: null
    option_name: async
    option_result: true
    options:
      Jigsaw:
        #progression_balancing: random-low
        number_of_pieces: random-range-250-450
        maximum_number_of_checks: random-range-250-450
        number_of_checks_out_of_logic: 10
  - option_name: game
    option_result: Jigsaw
    options:
      null:
        name: RePodSaw{NUMBER}
  - option_name: per_game_name
    option_result: false
    options:
      null:
        name: RePod{NUMBER}
