name: RePod{NUMBER}
game: Muse Dash
async: false
per_game_name: false

Muse Dash:
  # https://archipelago.gg/tutorial/Muse%20Dash/setup/en
  # Every time I look there's an update that breaks EVERYTHING but the options are sound.
  progression_balancing: 99
  accessibility: minimal
  dlc_packs:
    - maimai DX Limited-time Suite
    - Rin Len's Mirrorland
    - CHUNITHM COURSE MUSE
    - MSR Anthology
    - Muse Plus
    - Miku in Museland
  streamer_mode_enabled: false
  starting_song_count: 3
  additional_song_count: 40
  song_difficulty_mode: any
  song_difficulty_min: 4
  song_difficulty_max: 8
  grade_needed: pinks
  music_sheet_count_percentage: 20
  music_sheet_win_count_percentage: 80
  trap_count_percentage: 35
  death_link: true
  include_songs:
    - 39 Music!
    - Hand in Hand
    - Cynical Night Plan
    - God-ish
    - Darling Dance
    - Hatsune Creation Myth
    - The Vampire
    - Future Eve
    - Unknown Mother Goose
  exclude_songs: []
  #start_inventory: {"God-ish":1}

triggers:
  - option_category: null
    option_name: async
    option_result: true
    options:
      Muse Dash:
        accessibility: random
  - option_name: game
    option_result: Muse Dash
    options:
      null:
        name: RePodMuse{NUMBER}
  - option_name: per_game_name
    option_result: false
    options:
      null:
        name: RePod{NUMBER}
