name: RePod{NUMBER}
game: Ori and the Blind Forest
async: false
per_game_name: true
description: "Custom https://github.com/c-ostic/Archipelago/releases/latest"

Ori and the Blind Forest:
  # Easy FillError on solo gens
  progression_balancing: random-range-low-0-50
  accessibility:
    full: 1
    minimal: 2
  goal:
    all_skill_trees: 5 # old reliable
    all_maps: 3 # place all mapstones
    warmth_fragments: 1 # mcguffin hunt
    world_tour: 1 # mcguffin hunt. N/11 areas contain a relic in a random loc
    none: 0 # reach and finish escape
  warmth_fragments_available: 50 # 1-30-50
  warmth_fragments_required: 40 # 1-20-50
  logic_difficulty:
    casual: 1
    standard: 2
    expert: 5
    master: 1 # please no microledges
    glitched: 0
  keystone_logic:
    anywhere: 1
    area_specific: 3
  mapstone_logic:
    anywhere: 1
    area_specific: 3
    progressive: 1
  extra_mapstones: random-range-0-1 # 0-9
  deathlink_logic:
    disabled: 19
    partial: 1 # does not send instakills
    full: 0
  enable_lure:
    false: 1
    true: 3
  enable_damage_boost: # 12 ability cells. master+ req. ultra defense 
    false: 1
    true: 3
  enable_double_bash: # master
    false: 1
    true: 4
  enable_grenade_jump: # master
    false: 1
    true: 4
  enable_air_dash: # standard+, 3 ability cells
    false: 1
    true: 4
  enable_charge_dash: # expert+, 6 ability cells
    false: 1
    true: 4
  enable_triple_jump: # master, 12 ability cells
    false: 1
    true: 4
  enable_charge_flame_burn: # master, 3 ability cells
    false: 1
    true: 4
  enable_rekindle: # standard+, ghost lever in blackroot
    false: 1
    true: 4
  start_hints:
    - Dash

triggers:
  - option_category: null
    option_name: async
    option_result: true
    options:
      Ori and the Blind Forest:
        warmth_fragments_available: 50 # 1-50 (30)
        warmth_fragments_required: 45 # 1-50 (20)
        relic_count: random-range-8-11 # 1-11 (8)
        logic_difficulty:
          standard: 0
          expert: 3
          master: 2
        keystone_logic:
          anywhere: 3
          area_specific: 1
        mapstone_logic:
          anywhere: 3
          area_specific: 1
        extra_mapstones: 1
        deathlink_logic: partial
  - option_category: Ori and the Blind Forest
    option_name: logic_difficulty
    option_result: master
    options:
      Ori and the Blind Forest:
        deathlink_logic: disabled
        keystone_logic: area_specific
        mapstone_logic: area_specific
  - option_name: game
    option_result: Ori and the Blind Forest
    options:
      null:
        name: RePodOri{NUMBER} # OrePod...
  - option_name: per_game_name
    option_result: false
    options:
      null:
        name: RePod{NUMBER}
