name: RePod{NUMBER}
game: Ori and the Blind Forest
async: false
per_game_name: true
description: "Unsupported https://github.com/c-ostic/Archipelago/releases/latest"

Ori and the Blind Forest:
  # Easy FillError on solo gens
  progression_balancing: random-middle
  accessibility: random
  goal: all_skill_trees
  logic_difficulty:
    casual: 0
    standard: 1
    expert: 2
    master: 0 # grenade jumping is not sync safe
    glitched: 0
  keystone_logic:
    anywhere: 1
    area_specific: 0
  mapstone_logic:
    anywhere: 1
    area_specific: 0
  deathlink_logic:
    disabled: 1
    partial: 0 # does not send instakills
    full: 0

triggers:
  - option_category: null
    option_name: async
    option_result: true
    options:
      Ori and the Blind Forest:
        progression_balancing: random-low
        logic_difficulty:
          expert: 3
          master: 1
        keystone_logic:
          anywhere: 3
          area_specific: 1
        mapstone_logic:
          anywhere: 3
          area_specific: 1
        deathlink_logic: partial
  - option_name: game
    option_result: Ori and the Blind Forest
    options:
      null:
        name: RePodOri{NUMBER} # OrePod...
  - option_name: per_game_name
    option_result: false
    options:
      null:
        name: RePod{NUMBER}
