name: RePod{NUMBER}
game: Pokemon FireRed and LeafGreen
async: false
per_game_name: true
description: "Unsupported https://github.com/vyneras/Archipelago/releases/latest"
apworld: "https://github.com/vyneras/Archipelago/releases/latest"

Pokemon FireRed and LeafGreen:
  progression_balancing: random-low
  accessibility: random
  game_version: random
  kanto_only: false
  shuffle_badges: true
  shuffle_hidden: nonrecurring
  extra_key_items: true
  shuffle_fly_destination_unlocks: true
  itemfinder_required: logic
  flash_required: logic
  #remove_badge_requirement
  oaks_aide_route_2: 5
  oaks_aide_route_10: 10
  oaks_aide_route_11: 15
  oaks_aide_route_16: 20
  oaks_aide_route_15: 25
  viridian_city_roadblock:
    vanilla: 3
    early_parcel: 6
    open: 1
  pewter_city_roadblock:
    # Sets the requirement for passing the Pewter City Roadblock.
    #
    # - Open: The boy will not stop you from entering Route 3.
    # - Brock: The boy will stop you from entering Route 3 until you defeat Brock.
    # - Any Gym Leader: The boy will stop you from entering Route 3 until you defeat any Gym Leader.
    # - Boulder Badge: The boy will stop you from entering Route 3 until you have the Boulder Badge.
    # - Any Badge: The boy will stop you from entering Route 3 until you have a Badge.
    open: 1
    brock: 1
    any_gym: 1
    boulder_badge: 1
    any_badge: 1
  viridian_gym_requirement:
    badges: 3
    gyms: 2
  viridian_gym_count: random
  route22_gate_requirement:
    badges: 3
    gyms: 2
  route22_gate_count: random-high
  route23_guard_requirement:
    badges: 3
    gyms: 2
  route23_guard_count: random-high
  elite_four_requirement:
    badges: 3
    gyms: 2
  elite_four_count: 8
  cerulean_cave_requirement:
    vanilla: 0
    champion: 0
    restore_network: 1
    badges: 1
    gyms: 1
  cerulean_cave_count: random-middle
  level_scaling: spheres_and_distance
  #modify_trainer_levels
  wild_pokemon:
    vanilla: 0
    match_base_stats: 1
    match_type: 1
    match_base_stats_and_type: 1
    completely_random: 7
  wild_pokemon_groups: random
  starters:
    vanilla: 0
    match_base_stats: 1
    match_type: 1
    match_base_stats_and_type: 1
    completely_random: 5
  trainers:
    vanilla: 0
    match_base_stats: 1
    match_type: 1
    match_base_stats_and_type: 1
    completely_random: 5
  #trainer_blacklist
  legendary_pokemon:
    vanilla: 0
    match_base_stats: 1
    match_type: 1
    match_base_stats_and_type: 1
    completely_random: 5
  misc_pokemon:
    vanilla: 0
    match_base_stats: 1
    match_type: 1
    match_base_stats_and_type: 1
    completely_random: 3
  types: vanilla
  abilities: follow_evolutions
  ability_blacklist:
    - Truant
    - Wonder Guard
    - Arena Trap
    - Shadow Tag
    - Magnet Pull
  moves:
    vanilla: 1
    randomized: 2
    start_with_four_moves: 2
  #move_blacklist
  hm_compatibility: full
  tm_tutor_compatibility: random
  tm_tutor_moves: true
  reusable_tm_tutors: true
  min_catch_rate: 255
  guaranteed_catch: true
  exp_modifier: 225
  starting_money: 3939
  blind_trainers: true
  better_shops: true
  free_fly_location:
    exclude_indigo: 4
    any: 1
  turbo_a: true
  receive_item_messages: progression
  # Roll world modifiers (triggers)
  Modify Route 2: random-range-0-1
  Remove Cerulean Roadblocks: random-range-0-1
  Block Tunnels: random-range-0-1
  Modify Route 9: random-range-0-1
  Modify Route 10: random-range-0-1
  Block Tower: random-range-0-1
  Route 12 Boulders: random-range-0-1
  Modify Route 12: random-range-0-1
  Modify Route 16: random-range-0-1
  Route 23 Trees: random-range-0-1
  Modify Route 23: random-range-0-1
  Victory Road Rocks: random-range-0-1
  Early Gossipers: random-range-0-1
  Total Darkness: random-range-0-1

triggers:
  - option_name: Modify Route 2
    option_category: Pokemon FireRed and LeafGreen
    option_result: 1
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Modify Route 2
  - option_name: Remove Cerulean Roadblocks
    option_category: Pokemon FireRed and LeafGreen
    option_result: 1
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Remove Cerulean Roadblocks
  - option_name: Block Tunnels
    option_category: Pokemon FireRed and LeafGreen
    option_result: 1
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Block Tunnels
  - option_name: Modify Route 9
    option_category: Pokemon FireRed and LeafGreen
    option_result: 1
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Modify Route 9
  - option_name: Modify Route 10
    option_category: Pokemon FireRed and LeafGreen
    option_result: 1
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Modify Route 10
  - option_name: Block Tower
    option_category: Pokemon FireRed and LeafGreen
    option_result: 1
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Block Tower
  - option_name: Route 12 Boulders
    option_category: Pokemon FireRed and LeafGreen
    option_result: 1
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Route 12 Boulders
  - option_name: Modify Route 12
    option_category: Pokemon FireRed and LeafGreen
    option_result: 1
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Modify Route 12
  - option_name: Modify Route 16
    option_category: Pokemon FireRed and LeafGreen
    option_result: 1
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Modify Route 16
  - option_name: Route 23 Trees
    option_category: Pokemon FireRed and LeafGreen
    option_result: 1
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Route 23 Trees
  - option_name: Modify Route 23
    option_category: Pokemon FireRed and LeafGreen
    option_result: 1
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Modify Route 23
  - option_name: Victory Road Rocks
    option_category: Pokemon FireRed and LeafGreen
    option_result: 1
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Victory Road Rocks
  - option_name: Early Gossipers
    option_category: Pokemon FireRed and LeafGreen
    option_result: 1
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Early Gossipers
  - option_name: Total Darkness
    option_category: Pokemon FireRed and LeafGreen
    option_result: 1
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Total Darkness
  - option_category: null
    option_name: async
    option_result: true
    options:
      Pokemon FireRed and LeafGreen:
          goal: elite_four_rematch
          shuffle_hidden: all
          trainersanity: true
          famesanity: true
          pokemon_request_locations: true
          card_key:
            split: 4
            progressive: 1
          island_passes:
            progressive: 1
            split: 5
            progressive_split: 1
          modify_world_state:
            - Modify Route 2
            - Modify Route 10
          oaks_aide_route_2: 10
          oaks_aide_route_10: 20
          oaks_aide_route_11: 30
          oaks_aide_route_16: 40
          oaks_aide_route_15: 50
  - option_name: game
    option_result: Pokemon FireRed and LeafGreen
    options:
      null:
        name: RePodRG{NUMBER}
  - option_name: per_game_name
    option_result: false
    options:
      null:
        name: RePod{NUMBER}
