name: RePod{NUMBER}
game: Pokemon Red and Blue
async: false
per_game_name: true

Pokemon Red and Blue:
  # https://archipelago.gg/tutorial/Pokemon%20Red%20and%20Blue/setup/en
  progression_balancing: random-low
  accessibility: random
  game_version: random
  trainer_name: I
  rival_name: U
  elite_four_badges_condition: 8
  elite_four_key_items_condition: 0
  elite_four_pokedex_condition: 0
  victory_road_condition: random
  route_22_gate_condition: random
  viridian_gym_condition: random
  cerulean_cave_badges_condition: random
  cerulean_cave_key_items_condition: random
  route_3_condition: random
  robbed_house_officer: random
  second_fossil_check_condition: 3
  fossil_check_item_types: any
  exp_all: remove
  old_man: early_parcel
  badgesanity: true
  badges_needed_for_hm_moves: on
  key_items_only: false
  tea: random
  extra_key_items: false
  split_card_key: off
  all_elevators_locked: true
  extra_strength_boulders: random
  require_item_finder: false
  randomize_hidden_items: off
  randomize_pokedex: vanilla
  require_pokedex: true
  all_pokemon_seen: true
  oaks_aide_rt_2: 5
  oaks_aide_rt_11: 10
  oaks_aide_rt_15: 15
  stonesanity: false
  door_shuffle: simple
  warp_tile_shuffle: false
  randomize_rock_tunnel: false
  dark_rock_tunnel_logic: true
  free_fly_location:
    true: 3
    false: 1
  town_map_fly_location:
    true: 3
    false: 1
  blind_trainers: 100
  minimum_steps_between_encounters: 6
  level_scaling: by_spheres
  exp_modifier: 32
  randomize_wild_pokemon: completely_random
  area_1_to_1_mapping: false
  randomize_starter_pokemon: completely_random
  randomize_static_pokemon: completely_random
  randomize_legendary_pokemon: any
  catch_em_all: off
  randomize_pokemon_stats: vanilla
  randomize_pokemon_catch_rates: false
  minimum_catch_rate: 255
  randomize_trainer_parties: completely_random
  trainer_legendaries: true
  move_balancing: false
  fix_combat_bugs: true
  randomize_pokemon_movesets: completely_random
  confine_transform_to_ditto: true
  start_with_four_moves: true
  same_type_attack_bonus: true
  randomize_tm_moves: true
  tm_same_type_compatibility: -1
  tm_normal_type_compatibility: -1
  tm_other_type_compatibility: -1
  hm_same_type_compatibility: 100
  hm_normal_type_compatibility: 100
  hm_other_type_compatibility: 100
  inherit_tm_hm_compatibility: false
  randomize_move_types: false
  randomize_pokemon_types: vanilla
  secondary_type_chance: -1
  randomize_type_chart: vanilla
  normal_matchups: 143
  super_effective_matchups: 38
  not_very_effective_matchups: 38
  immunity_matchups: 6
  safari_zone_normal_battles: false
  normalize_encounter_chances: true
  reusable_tms: true
  better_shops: on
  master_ball_price: 0
  starting_money: 3001
  lose_money_on_blackout: false
  poke_doll_skip: patched
  bicycle_gate_skips: patched
  trap_percentage: 10
  poison_trap_weight: medium
  fire_trap_weight: medium
  paralyze_trap_weight: medium
  sleep_trap_weight: medium
  ice_trap_weight: disabled
  randomize_pokemon_palettes: completely_random

triggers:
  - option_category: null
    option_name: async
    option_result: true
    options:
      Pokemon Red and Blue:
        rival_name: FNSHING
        death_link: true
        all_pokemon_seen: false
        oaks_aide_rt_2: 10
        oaks_aide_rt_11: 30
        oaks_aide_rt_15: 50
        door_shuffle:
            insanity: 3
            decoupled: 1
        extra_key_items: true
        split_card_key: true
        warp_tile_shuffle: mixed
        randomize_rock_tunnel: true
        dark_rock_tunnel_logic: true
        prizesanity: true
        trainersanity: full
        dexsanity: full
  - option_name: game
    option_result: Pokemon Red and Blue
    options:
      null:
        name: RePodRB{NUMBER}
  - option_name: per_game_name
    option_result: false
    options:
      null:
        name: RePod{NUMBER}
