name: RePod{NUMBER}
game: Pokemon FireRed and LeafGreen
async: false
per_game_name: true
description: "Unsupported https://github.com/vyneras/Archipelago/releases/latest"

Pokemon FireRed and LeafGreen:
  progression_balancing: random-low
  accessibility: random
  game_version: random
  goal: elite_four # _rematch
  kanto_only: false
  random_starting_town: true
  shuffle_badges: true
  shuffle_hidden: all
  extra_key_items: true
  famesanity: true
  shuffle_fly_destination_unlocks: all
  pokemon_request_locations: true
  shuffle_running_shoes: start_with
  card_key:
    vanilla: 1
    split: 2
    progressive: 2
  island_passes:
    vanilla: 1
    progressive: 2
    split: 2
    progressive_split: 2
  split_teas:
    false: 1
    true: 9
  itemfinder_required: off
  flash_required: logic
  fame_checker_required: false
  #remove_badge_requirement
  oaks_aide_route_2: 1
  oaks_aide_route_10: 2
  oaks_aide_route_11: 3
  oaks_aide_route_16: 4
  oaks_aide_route_15: 5
  viridian_city_roadblock:
    vanilla: 3
    early_parcel: 6
    open: 1
  pewter_city_roadblock:
    open: 1
    brock: 1
    any_gym: 1
    boulder_badge: 1
    any_badge: 1
  viridian_gym_requirement:
    badges: 3
    gyms: 2
  viridian_gym_count: random
  route22_gate_requirement:
    badges: 3
    gyms: 2
  route22_gate_count: random-high
  route23_guard_requirement:
    badges: 3
    gyms: 2
  route23_guard_count: random-high
  elite_four_requirement:
    badges: 3
    gyms: 2
  elite_four_count: 8
  cerulean_cave_requirement:
    vanilla: 0
    champion: 0
    restore_network: 1
    badges: 1
    gyms: 1
  cerulean_cave_count: random-middle
  level_scaling: spheres
  #modify_trainer_levels
  force_fully_evolved: species
  wild_pokemon:
    vanilla: 0
    match_base_stats: 1
    match_type: 1
    match_base_stats_and_type: 1
    completely_random: 7
  wild_pokemon_groups: random
  starters:
    vanilla: 0
    match_base_stats: 1
    match_type: 1
    match_base_stats_and_type: 1
    completely_random: 7
  trainers:
    vanilla: 0
    match_base_stats: 1
    match_type: 1
    match_base_stats_and_type: 1
    completely_random: 7
  #trainer_blacklist
  legendary_pokemon:
    vanilla: 0
    match_base_stats: 1
    match_type: 1
    match_base_stats_and_type: 1
    completely_random: 7
  misc_pokemon:
    vanilla: 0
    match_base_stats: 1
    match_type: 1
    match_base_stats_and_type: 1
    completely_random: 7
  types: vanilla
  abilities: follow_evolutions
  ability_blacklist:
    - Truant
    - Wonder Guard
    - Arena Trap
    - Shadow Tag
    - Magnet Pull
  moves:
    vanilla: 1
    randomized: 2
    start_with_four_moves: 2
  #move_blacklist
  hm_compatibility: full
  tm_tutor_compatibility: random
  tm_tutor_moves: true
  reusable_tm_tutors: true
  min_catch_rate: 255
  guaranteed_catch: true
  normalize_encounter_rates: true
  all_pokemon_seen: true
  exp_modifier: 225
  starting_money: 3939
  blind_trainers: true
  better_shops: true
  free_fly_location:
    exclude_indigo: 4
    any: 1
  town_map_fly_location:
    off: 1
    exclude_indigo: 4
    any: 1
  turbo_a: true
  receive_item_messages: progression
  randomize_music: true
  randomize_fanfares: true
  provide_hints: true
  # Roll world modifiers (triggers)
  Modify Route 2:
    Yes: 2
    No: 1
  Remove Cerulean Roadblocks:
    Yes: 2
    No: 1
  Block Tunnels:
    Yes: 2
    No: 1
  Modify Route 9:
    Yes: 2
    No: 1
  Modify Route 10:
    Yes: 2
    No: 1
  Block Tower:
    Yes: 2
    No: 1
  Route 12 Boulders:
    Yes: 2
    No: 1
  Modify Route 12:
    Yes: 2
    No: 1
  Modify Route 16:
    Yes: 2
    No: 1
  Open Silph:
    Yes: 2
    No: 1
  Remove Saffron Rockets:
    Yes: 2
    No: 1
  Route 23 Trees:
    Yes: 2
    No: 1
  Modify Route 23:
    Yes: 2
    No: 1
  Victory Road Rocks:
    Yes: 2
    No: 1
  Early Gossipers:
    Yes: 2
    No: 1
  Total Darkness:
    Yes: 2
    No: 1
  Block Vermilion Sailing:
    Yes: 2
    No: 1
  # Caves
  Dark Mt Moon:
    Yes: 2
    No: 1
  Dark Digletts Cave:
    Yes: 2
    No: 1
  Dark Victory Road:
    Yes: 2
    No: 1

triggers:
  - option_category: null
    option_name: async
    option_result: true
    options:
      Pokemon FireRed and LeafGreen:
          goal: elite_four_rematch
          shuffle_hidden: all
          trainersanity: all # none-0-456-all
          dexsanity: all # none-1-386-all
          famesanity: true
          all_pokemon_seen: false
          pokemon_request_locations: true
          card_key:
            split: 4
            progressive: 1
          island_passes:
            progressive: 1
            split: 5
            progressive_split: 1
          oaks_aide_route_2: 30
          oaks_aide_route_10: 70
          oaks_aide_route_11: 110
          oaks_aide_route_16: 150
          oaks_aide_route_15: 190
  # FRLG World state
  - option_name: Modify Route 2
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Modify Route 2
  - option_name: Remove Cerulean Roadblocks
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Remove Cerulean Roadblocks
  - option_name: Block Tunnels
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Block Tunnels
  - option_name: Modify Route 9
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Modify Route 9
  - option_name: Modify Route 10
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Modify Route 10
  - option_name: Block Tower
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Block Tower
  - option_name: Route 12 Boulders
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Route 12 Boulders
  - option_name: Modify Route 12
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Modify Route 12
  - option_name: Modify Route 16
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Modify Route 16
  - option_name: Open Silph
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Open Silph
  - option_name: Remove Saffron Rockets
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Remove Saffron Rockets
  - option_name: Route 23 Trees
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Route 23 Trees
  - option_name: Modify Route 23
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Modify Route 23
  - option_name: Victory Road Rocks
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Victory Road Rocks
  - option_name: Early Gossipers
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Early Gossipers
  - option_name: Total Darkness
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Total Darkness
  - option_name: Block Vermilion Sailing
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Block Vermilion Sailing
  # FRLG Dark Caves
  - option_name: Dark Mt Moon
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +additional_dark_caves:
          - Mt. Moon
  - option_name: Dark Digletts Cave
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +additional_dark_caves:
          - Diglett's Cave
  - option_name: Dark Victory Road
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +additional_dark_caves:
          - Victory Road
  - option_name: game
    option_result: Pokemon FireRed and LeafGreen
    options:
      null:
        name: RePodRG{NUMBER}
  - option_name: per_game_name
    option_result: false
    options:
      null:
        name: RePod{NUMBER}
