name: RePod{NUMBER}
game: Pokemon Crystal
async: false
per_game_name: true
description: "Unsupported https://github.com/gerbiljames/Archipelago/releases/latest"

Pokemon Crystal:
  progression_balancing: random-low
  accessibility: random
  goal:
    elite_four: 1
    red: 0
  johto_only: off # include_silver_cave = Red
  elite_four_badges: 8 # 1-[8]-16
  red_badges: 16 # 1-[16]
  mt_silver_badges: 16 # 1-[16]
  radio_tower_badges: 7 # 1-[7]-16
  randomize_badges: completely_random
  randomize_hidden_items: true
  require_itemfinder: false
  route_32_condition: egg_from_aide # egg_from_aide/any_badge/none
  trainersanity: false
  trainersanity_alerts: message_box # no_alerts/message_box/sound_only
  randomize_pokegear: true
  randomize_berry_trees: true
  randomize_starters: completely_random
  starters_bst_average: normal_starters
  randomize_wilds: true
  force_fully_evolved: 35
  normalize_encounter_rates: true
  randomize_static_pokemon: true
  level_scaling: spheres # off/spheres/spheres_and_distance
  randomize_trades: both
  randomize_trainer_parties: completely_random
  boost_trainers: vanilla
  trainer_level_boost: 1
  randomize_learnsets: start_with_four_moves
  randomize_tm_moves: true
  tm_compatibility: 50
  hm_compatibility: 100
  randomize_base_stats: random
  randomize_types: vanilla
  randomize_palettes: random
  randomize_music: true
  early_fly:
    false: 1
    true: 4
  free_fly_location:
    off: 1
    free_fly: 2
    free_fly_and_map_card: 2
  hm_badge_requirements:
    # vanilla: HMs require their vanilla badges
    # no_badges: HMs do not require a badge to use
    # add_kanto: HMs can be used with the Johto or Kanto badge
    vanilla: 1
    no_badges: 0
    add_kanto: 3
  remove_ilex_cut_tree:
    false: 4
    true: 1
  east_west_underground:
    false: 3
    true: 1
  undergrounds_require_power:
    both: 4
    north_south: 1
    east_west: 1
    neither: 1
  reusable_tms: true
  guaranteed_catch: true
  minimum_catch_rate: 255
  blind_trainers: true
  skip_elite_four:
    false: 4
    true: 1
  better_marts: true
  experience_modifier: 50
  phone_trap_weight: random
  sleep_trap_weight: 0
  poison_trap_weight: 0
  burn_trap_weight: 0
  freeze_trap_weight: 0
  paralysis_trap_weight: 0
  remote_items: true
  item_receive_sound: true
  enable_mischief: true

triggers:
  - option_category: null
    option_name: async
    option_result: true
    options:
      Pokemon Crystal:
        trainersanity:
          false: 1
          true: 4
        goal: red
  - option_name: game
    option_result: Pokemon Crystal
    options:
      null:
        name: RePodCRY{NUMBER}
  - option_name: per_game_name
    option_result: false
    options:
      null:
        name: RePod{NUMBER}
