name: RePod{NUMBER}
game: Pokemon Crystal
async: false
per_game_name: true
description: "Unsupported https://github.com/gerbiljames/Archipelago/releases/latest"

Pokemon Crystal:
  progression_balancing: random-low
  accessibility: random
  goal:
    elite_four: 1
    red: 0
  johto_only: off # include_silver_cave = Red
  elite_four_badges: 8 # 1-[8]-16
  red_badges: 16 # 1-[16]
  mt_silver_badges: 16 # 1-[16]
  radio_tower_badges: 7 # 1-[7]-16
  randomize_badges: completely_random
  randomize_hidden_items: true
  require_itemfinder: logically_required
  route_32_condition: egg_from_aide # egg_from_aide/any_badge/none
  kanto_access_condition: wake_snorlax # wake_snorlax/badge_count/become_champion
  kanto_access_badges: 8 # 1-[8]-16
  red_gyarados_access:
    vanilla: 1
    whirlpoo: 4
  route_2_access: # the cave exit below Pewter
    vanilla: 1
    ledge: 1
    open: 1
  route_3_access: # Pewter towards Mt Moon
    vanilla: 1
    boulder_badge: 2
  blackthorn_dark_cave_access:
    vanilla: 1
    waterfall: 2 # Violet side: waterfall+flash+surf
  national_park_access:
    vanilla: 1
    bicycle: 3
  trainersanity: false
  trainersanity_alerts: message_box # no_alerts/message_box/sound_only
  randomize_pokegear: true
  randomize_berry_trees: true
  randomize_starters: completely_random
  starters_bst_average: normal_starters
  randomize_wilds: true
  force_fully_evolved: 35
  normalize_encounter_rates: true
  randomize_static_pokemon: true
  level_scaling: spheres_and_distance # off/spheres/spheres_and_distance
  randomize_trades: both
  randomize_trainer_parties: completely_random
  boost_trainers: vanilla
  trainer_level_boost: 1
  randomize_learnsets: start_with_four_moves
  randomize_tm_moves: true
  tm_compatibility: 50
  hm_compatibility: 100
  randomize_base_stats: random
  randomize_types: vanilla
  randomize_palettes: random
  randomize_music: true
  early_fly:
    false: 1
    true: 4
  free_fly_location:
    off: 1
    free_fly: 2
    free_fly_and_map_card: 2
  hm_badge_requirements:
    # vanilla: HMs require their vanilla badges
    # no_badges: HMs do not require a badge to use
    # add_kanto: HMs can be used with the Johto or Kanto badge
    vanilla: 1
    no_badges: 0
    add_kanto: 3
  remove_ilex_cut_tree:
    false: 4
    true: 1
  #saffron_gatehouse_tea TODO make triggers
  east_west_underground:
    false: 3
    true: 1
  undergrounds_require_power:
    both: 4
    north_south: 1
    east_west: 1
    neither: 1
  reusable_tms: true
  guaranteed_catch: true
  minimum_catch_rate: 255
  blind_trainers: true
  skip_elite_four:
    false: 3
    true: 2
  better_marts: true
  experience_modifier: 50
  phone_trap_weight: random
  sleep_trap_weight: 1 # [0]-8
  poison_trap_weight: 1 # [0]-8
  burn_trap_weight: 1 # [0]-8
  freeze_trap_weight: 1 # [0]-8
  paralysis_trap_weight: 1 # [0]-8
  remote_items: true
  item_receive_sound: true
  game_options:
    text_speed: instant
    battle_shfit: set
    battle_animations: speedy
    sound: stereo
    menu_account: off
    text_frame: random-range-1-8
    bike_music: off
    surf_music: off
    skip_nicknames: true
    auto_run: true
    fast_egg_hatch: on
    fast_egg_make: on
    rods_always_work: on
    exp_distribution: gen2
    catch_exp: off
    poison_flicker: off
    turbo_button: a_or_b
    time_of_day: nite
    battle_move_stats: on
  enable_mischief: true

triggers:
  - option_category: null
    option_name: async
    option_result: true
    options:
      Pokemon Crystal:
        trainersanity:
          false: 1
          true: 4
        goal: red
  - option_name: game
    option_result: Pokemon Crystal
    options:
      null:
        name: RePodCRY{NUMBER}
  - option_name: per_game_name
    option_result: false
    options:
      null:
        name: RePod{NUMBER}
