name: RePod{NUMBER}
game: Pokemon FireRed and LeafGreen
async: false
per_game_name: true
description: "Custom https://github.com/vyneras/Archipelago/releases/latest"

Pokemon FireRed and LeafGreen:
  progression_balancing: random-low
  accessibility: random
  game_version: random
  goal: champion # _rematch
  kanto_only: false
  random_starting_town: true
  dungeon_entrance_shuffle: simple # off/simple/restricted/full
  randomize_fly_destinations: true
  shuffle_badges: true
  shuffle_hidden: all
  extra_key_items: true
  shopsanity: true
  # shop_prices
  # minimum_shop_price
  # maximum_shop_price
  famesanity: true
  shuffle_fly_unlocks: all
  pokemon_request_locations: true
  shuffle_running_shoes: start_with
  shuffle_berry_pouch: true
  shuffle_tm_case:
    true: 1
    false: 3
  card_key:
    vanilla: 1
    split: 2
    progressive: 2
  island_passes:
    vanilla: 1
    progressive: 2
    split: 2
    progressive_split: 2
  split_teas:
    false: 1
    true: 9
  gym_keys:
    true: 2
    false: 3
  itemfinder_required: off
  flash_required: logic
  fame_checker_required: false
  viridian_city_roadblock:
    vanilla: 3
    early_parcel: 6
    open: 1
  pewter_city_roadblock:
    open: 1
    brock: 1
    any_gym: 1
    boulder_badge: 1
    any_badge: 1
  #remove_badge_requirement
  oaks_aide_route_2: 1
  oaks_aide_route_10: 2
  oaks_aide_route_11: 3
  oaks_aide_route_16: 4
  oaks_aide_route_15: 5
  viridian_gym_requirement:
    badges: 3
    gyms: 2
  viridian_gym_count: random
  route22_gate_requirement:
    badges: 3
    gyms: 2
  route22_gate_count: random-high
  route23_guard_requirement:
    badges: 3
    gyms: 2
  route23_guard_count: random-high
  elite_four_requirement:
    badges: 3
    gyms: 2
  elite_four_count: 8
  cerulean_cave_requirement:
    vanilla: 0
    champion: 0
    restore_network: 1
    badges: 1
    gyms: 1
  cerulean_cave_count: random-middle
  level_scaling: spheres
  #modify_trainer_levels
  force_fully_evolved: species
  wild_pokemon:
    vanilla: 0
    match_base_stats: 1
    match_type: 1
    match_base_stats_and_type: 1
    completely_random: 7
  wild_pokemon_groups: random
  starters:
    vanilla: 0
    match_base_stats: 1
    match_type: 1
    match_base_stats_and_type: 1
    completely_random: 7
  trainers:
    vanilla: 0
    match_base_stats: 1
    match_type: 1
    match_base_stats_and_type: 1
    completely_random: 7
  #trainer_blacklist
  legendary_pokemon:
    vanilla: 0
    match_base_stats: 1
    match_type: 1
    match_base_stats_and_type: 1
    completely_random: 7
  misc_pokemon:
    vanilla: 0
    match_base_stats: 1
    match_type: 1
    match_base_stats_and_type: 1
    completely_random: 7
  types: vanilla
  abilities: follow_evolutions
  ability_blacklist: ['Arena Trap','Magnet Pull','Shadow Tag','Truant','Wonder Guard']
  moves:
    vanilla: 1
    randomized: 2
    start_with_four_moves: 2
  #move_blacklist
  # physical_special_split
  hm_compatibility: full
  tm_tutor_compatibility: random
  tm_tutor_moves: true
  reusable_tm_tutors: true
  min_catch_rate: 255
  starting_money: 3939
  better_shops: true
  free_fly_location:
    true: 3
    false: 1
  town_map_fly_location:
    true: 1
    false: 3
  remote_items: true
  randomize_music: true
  randomize_fanfares: true
  game_options:
    Auto Run: 'On'
    Battle Scene: 'Off'
    Battle Style: 'Set'
    Bike Music: 'Off'
    Blind Trainers: 'On'
    Button Mode: 'L=A'
    Encounter Rates: 'Normalized'
    Experience: 'Double'
    Frame: 1
    Guaranteed Catch: 'On'
    Item Messages: 'Progression'
    Low HP Beep: 'Off'
    Show Effectiveness: 'On'
    Skip Fanfares: 'On'
    Sound: 'Stereo'
    Surf Music: 'Off'
    Text Speed: 'Instant'
    Turbo A: 'On'
  provide_hints: all
  death_link: false
  # Roll world modifiers (triggers)
  Modify Route 2:
    Yes: 2
    No: 1
  Remove Cerulean Roadblocks:
    Yes: 2
    No: 1
  Block Tunnels:
    Yes: 2
    No: 1
  Modify Route 9:
    Yes: 2
    No: 1
  Modify Route 10:
    Yes: 2
    No: 1
  Block Tower:
    Yes: 2
    No: 1
  Route 12 Boulders:
    Yes: 2
    No: 1
  Modify Route 12:
    Yes: 2
    No: 1
  Modify Route 16:
    Yes: 2
    No: 1
  Open Silph:
    Yes: 2
    No: 1
  Remove Saffron Rockets:
    Yes: 2
    No: 1
  Route 23 Trees:
    Yes: 2
    No: 1
  Modify Route 23:
    Yes: 2
    No: 1
  Victory Road Rocks:
    Yes: 2
    No: 1
  Early Gossipers:
    Yes: 2
    No: 1
  Total Darkness:
    Yes: 2
    No: 1
  Block Vermilion Sailing:
    Yes: 2
    No: 1
  # Caves
  Dark Mt Moon:
    Yes: 2
    No: 1
  Dark Digletts Cave:
    Yes: 2
    No: 1
  Dark Victory Road:
    Yes: 2
    No: 1

triggers:
  - option_category: null
    option_name: async
    option_result: true
    options:
      Pokemon FireRed and LeafGreen:
          goal: champion_rematch
          skip_elite_four: false
          shuffle_hidden: all
          trainersanity: all # none-0-456-all
          dexsanity: all # none-1-386-all
          famesanity: true
          all_pokemon_seen: false
          pokemon_request_locations: true
          card_key:
            split: 4
            progressive: 1
          island_passes:
            progressive: 1
            split: 5
            progressive_split: 1
          oaks_aide_route_2: 10
          oaks_aide_route_10: 20
          oaks_aide_route_11: 30
          oaks_aide_route_16: 40
          oaks_aide_route_15: 50
          death_link: true
  # FRLG World state
  - option_name: Modify Route 2
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Modify Route 2
  - option_name: Remove Cerulean Roadblocks
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Remove Cerulean Roadblocks
  - option_name: Block Tunnels
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Block Tunnels
  - option_name: Modify Route 9
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Modify Route 9
  - option_name: Modify Route 10
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Modify Route 10
  - option_name: Block Tower
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Block Tower
  - option_name: Route 12 Boulders
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Route 12 Boulders
  - option_name: Modify Route 12
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Modify Route 12
  - option_name: Modify Route 16
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Modify Route 16
  - option_name: Open Silph
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Open Silph
  - option_name: Remove Saffron Rockets
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Remove Saffron Rockets
  - option_name: Route 23 Trees
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Route 23 Trees
  - option_name: Modify Route 23
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Modify Route 23
  - option_name: Victory Road Rocks
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Victory Road Rocks
  - option_name: Early Gossipers
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Early Gossipers
  - option_name: Total Darkness
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Total Darkness
  - option_name: Block Vermilion Sailing
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +modify_world_state:
          - Block Vermilion Sailing
  # FRLG Dark Caves
  - option_name: Dark Mt Moon
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +additional_dark_caves:
          - Mt. Moon
  - option_name: Dark Digletts Cave
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +additional_dark_caves:
          - Diglett's Cave
  - option_name: Dark Victory Road
    option_category: Pokemon FireRed and LeafGreen
    option_result: Yes
    options:
      Pokemon FireRed and LeafGreen:
        +additional_dark_caves:
          - Victory Road
  - option_name: game
    option_result: Pokemon FireRed and LeafGreen
    options:
      null:
        name: RePodRG{NUMBER}
  - option_name: per_game_name
    option_result: false
    options:
      null:
        name: RePod{NUMBER}
