name: RePod{NUMBER}
game: Sonic the Hedgehog 1
async: false
per_game_name: true
# For now, the releases are only Sonic 1. Intent seems to be PR for official then another branch.
description: "Unsupported https://github.com/kaithar/Archipelago/releases/latest"
weight: 0

Sonic the Hedgehog 1:
  progression_balancing: random-middle
  accessibility: random
  no_local_keys: false
  allow_disable_goal: true
  allow_disable_r: true
  hard_mode: false # static ring count 0, only drop 6 rings
  ring_goal: 100 # 0-150, amount of MW rings found to clear
  available_rings: 185 # 0-185, total rings in pool
  boring_filler: false # Enable to take the fun out of the junk filler items

triggers:
  - option_category: null
    option_name: async
    option_result: true
    options:
      Sonic the Hedgehog 1:
        progression_balancing: random-low
        ring_goal: 150
  - option_name: game
    option_result: Sonic the Hedgehog 1
    options:
      null:
        name: RePodS1{NUMBER}
  - option_name: per_game_name
    option_result: false
    options:
      null:
        name: RePod{NUMBER}
