name: RePod{NUMBER}
game: The Messenger
async: false
per_game_name: true

The Messenger:
  progression_balancing: random-middle
  accessibility: random
  death_link: false
  logic_level:
    normal: 1
    hard: 0
  shuffle_shards: false
  limited_movement: false
  early_meditation: false
  available_portals: 6 # 3-6
  shuffle_portals:
    none: 1
    shops: 0
    checkpoints: 0
    anywhere: 0
  goal:
    open_music_box: 1
    power_seal_hunt: 0
  music_box: true
  notes_needed: 6 # 1-6
  total_seals: 45 # 1-85
  percent_seals_required: random-range-60-75 # 10-100
  traps: false
  shop_price: 100 # % mult

triggers:
  - option_category: null
    option_name: async
    option_result: true
    options:
      The Messenger:
        progression_balancing: random-low
        death_link: true
        shuffle_shards: true
        logic_level:
          normal: 9 # may require damage boosts
          hard: 1 # leashing, clips, tighter dmg boosting
        limited_movement:
          false: 9
          true: 1 # remove either rope or wingsuit. forces logic_level hard and accessibility minimal
        goal:
          open_music_box: 3
          power_seal_hunt: 1
        notes_needed: 6
        total_seals: 45
        percent_seals_required: random-range-80-95
        traps: true
  - option_name: game
    option_result: The Messenger
    options:
      null:
        name: RePodMess{NUMBER}
  - option_name: per_game_name
    option_result: false
    options:
      null:
        name: RePod{NUMBER}
