name: RePod{NUMBER}
game: Void Stranger
async: false
per_game_name: true
description: "Custom https://github.com/CriminalPancake/void-stranger-ap/raw/refs/tags/v0.8.0/voidstranger.apworld"
weight: 0

Void Stranger:
  progression_balancing: random-middle
  accessibility: random
  locustsanity: true # 3x chests force an equivalent 3x locust item. atoning changes, F9 menu.
  brandsanity: false # murals as checks, brand required to carve
  idolsanity: false # one check each once received
  shortcutsanity: false # no locust reqs for mon, mon gives checks 
  skipcutscenes: true # finale only

triggers:
  - option_category: null
    option_name: async
    option_result: true
    options:
      Void Stranger:
        progression_balancing: random-low
        locustsanity: true
        brandsanity: true
        idolsanity: true
        shortcutsanity: true
  - option_name: game
    option_result: Void Stranger
    options:
      null:
        name: RePodVoid{NUMBER}
  - option_name: per_game_name
    option_result: false
    options:
      null:
        name: RePod{NUMBER}
