name: RePod{NUMBER}
game: Yoshi's Island
async: false
per_game_name: true

Yoshi's Island:
  progression_balancing: random-low
  accessibility: random
  starting_world: world_1
  starting_lives: 69
  goal:
    bowser: 1
    luigi_hunt: 0
  luigi_pieces_required: 25 # 1-100
  luigi_pieces_in_pool: 50 # 1-100
  extras_enabled: false
  minigame_checks: none
  split_extras: false
  split_bonus: false
  hidden_object_visibility: coins_only
  add_secretlens: false
  shuffle_midrings: false
  stage_logic: strict
  item_logic: false
  disable_autoscroll: false
  softlock_prevention: true
  castle_open_condition: 5
  castle_clear_condition: 0
  bowser_door_mode: manual
  level_shuffle: disabled
  boss_shuffle: false
  yoshi_colors: random_order
  yoshi_singularity_color: random
  baby_mario_sound:
    normal: 50
    disabled: 0
    random_sound_effect: 0
  traps_enabled: false
  trap_percent: 10
  death_link: false

triggers:
  - option_category: null
    option_name: async
    option_result: true
    options:
      Yoshi's Island:
        death_link: true
  - option_name: game
    option_result: Yoshi's Island
    options:
      null:
        name: RePodYI{NUMBER}
  - option_name: per_game_name
    option_result: false
    options:
      null:
        name: RePod{NUMBER}
