name: RePod{NUMBER}
game: Yu-Gi-Oh! Forbidden Memories
async: false
per_game_name: true
description: "Unsupported https://github.com/sg4e/Archipelago/releases/latest"
apworld: "https://github.com/sg4e/Archipelago/releases/latest"

Yu-Gi-Oh! Forbidden Memories:
  # BizHawk client + lua connector
  progression_balancing: random-low
  accessibility: random
  duelist_progression: random
  local_starchips: false
  final6_progression: fixed
  final6_sequence: first_5_shuffled
  atec_logic:
    off: 0
    pegasus_only: 1
    hundo_atecs: 0 # Pegasus, Kaiba, Mage Soldier, Meadow Mage, and NiteMare
    all: 0
  atec_trap: acid_trap_hole
    # The weakest (i.e. lowest mox Life Point activation) trap card with which you can be expected to ATec a duelist.
    # ATecs will be in logic as soon as you have access to a duelist who drops this card or a stronger trap card,
    # excluding their SATec drop pool. Your other ATec settings are still respected.
    #
    # Note that Fake Trap puts ATecs in logic right from the start since it drops off of Simon Muran and Simon Muran is
    # always unlocked.
    acid_trap_hole: 50
    invisible_wire: 0
    fake_trap: 0
  drop_rate_logic: 64
  death_link: false

triggers:
  - option_category: null
    option_name: async
    option_result: true
    options:
      Yu-Gi-Oh! Forbidden Memories:
        randomize_duelist_order:
          false: 1
          true: 3
        item_mode:
          starchips: 1
          cards: 4 # 678 > 358 checks
        unobtainable_rewards:
          false: 1
          true: 4 # requires item_mode:cards
        atec_logic:
          pegasus_only: 4
          hundo_atecs: 2
          all: 1 # Pain
        atec_trap:
          acid_trap_hole: 4 # <3000 ATK
          invisible_wire: 2 # <2000 ATK
          fake_trap: 1      # Pain. Simon Muran from the start.
        final6_progression:
          shuffled: 1
          all_6_shuffled: 0
        drop_rate_logic: random-range-low-0-24
        death_link: true
  - option_name: game
    option_result: Yu-Gi-Oh! Forbidden Memories
    options:
      null:
        name: RePodFM{NUMBER}
  - option_name: per_game_name
    option_result: false
    options:
      null:
        name: RePod{NUMBER}
