name: RePod{NUMBER}
game: Yu-Gi-Oh! 2006
async: false
per_game_name: true

Yu-Gi-Oh! 2006:
  # https://archipelago.gg/games/Yu-Gi-Oh!%202006/player-options
  # Currently just the default generation options with a few tweaks
  progression_balancing: random-low
  accessibility: random
  structure_deck:
    # dragons_roar zombie_madness blazing_destruction fury_from_the_deep warriors_triumph spellcasters_judgement worst random_deck random_singles random_playsets custom
    worst: 1
    random_deck: 1 # old behavior, any of the starters
    random_singles: 1 # completely random no dupes
    random_playsets: 1 # 14 completely random playsets of 3.
  #starter_deck: vanilla remove random_singles random_playsets
  banlist: september_2005
  #final_campaign_boss_unlock_condition: campaign_opponents
  #fourth_tier_5_campaign_boss_unlock_condition: campaign_opponents # deprecated
  #third_tier_5_campaign_boss_unlock_condition: campaign_opponents # deprecated
  final_campaign_boss_challenges: 10
  fourth_tier_5_campaign_boss_challenges: 5
  third_tier_5_campaign_boss_challenges: 2
  final_campaign_boss_campaign_opponents: 12
  fourth_tier_5_campaign_boss_campaign_opponents: 7
  third_tier_5_campaign_boss_campaign_opponents: 3
  number_of_challenges: 91
  starting_money: 3000
  money_reward_multiplier: 20
  normalize_booster_pack_prices: true
  booster_pack_prices: 100
  normalize_booster_pack_rarities: true
  add_empty_banlist: true
  campaign_opponents_shuffle:
    true: 3
    false: 1
  ocg_arts:
    true: 1
    false: 3

triggers:
  - option_category: null
    option_name: async
    option_result: true
    options:
      Yu-Gi-Oh! 2006:
          # No way to tell what was picked without doing them.
          #final_campaign_boss_unlock_condition:
          #  campaign_opponents: 3
          #  challenges: 1
          #fourth_tier_5_campaign_boss_unlock_condition:
          #  campaign_opponents: 3
          #  challenges: 1
          #third_tier_5_campaign_boss_unlock_condition:
          #  campaign_opponents: 3
          #  challenges: 1
          # _challenges are 0-91, might want to range these
          final_campaign_boss_challenges: 39
          fourth_tier_5_campaign_boss_challenges: 26
          third_tier_5_campaign_boss_challenges: 13
          # _opponents are 0-24 - (final/4th/3rd 0/1/2)
          final_campaign_boss_campaign_opponents: 18
          fourth_tier_5_campaign_boss_campaign_opponents: 13
          third_tier_5_campaign_boss_campaign_opponents: 8
          # 0-91 challenges, imbalanced with above may result in a fast/easier game
          # 74 base + 91 challenges = 165 checks
          number_of_challenges: 91
          normalize_booster_pack_rarities: false
          randomize_pack_contents:
            vanilla: 0
            shuffle: 2
            chaos: 3
  - option_name: game
    option_result: Yu-Gi-Oh! 2006
    options:
      null:
        name: RePod06{NUMBER}
  - option_name: per_game_name
    option_result: false
    options:
      null:
        name: RePod{NUMBER}
